name: Simple Python CI/CD Pipeline

on: [push]

jobs:
  lint:
    runs-on: ububtu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
  test:
    runs-on: ububtu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
  build:
    runs-on: ububtu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
